// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_0pKBaIeGoIMY6LKRZB2R7jKXF5uEO8',
    appId: '1:249052343069:web:0ca4b9f81547a33af2cff4',
    messagingSenderId: '249052343069',
    projectId: 'kelompok2project-disposisi',
    authDomain: 'kelompok2project-disposisi.firebaseapp.com',
    storageBucket: 'kelompok2project-disposisi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89R0QKnYNaEo5apLDygQvwfmqTAY1rHs',
    appId: '1:249052343069:android:fdd8899ec89fb6f3f2cff4',
    messagingSenderId: '249052343069',
    projectId: 'kelompok2project-disposisi',
    storageBucket: 'kelompok2project-disposisi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJUH2cp8uEHi7voWVu5LEvTEowkhDcUkA',
    appId: '1:249052343069:ios:594fbe2058203b0ef2cff4',
    messagingSenderId: '249052343069',
    projectId: 'kelompok2project-disposisi',
    storageBucket: 'kelompok2project-disposisi.appspot.com',
    iosClientId: '249052343069-uqlofr2li7edtgrfoa8ce28lkttmuf1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelompok2disposisi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJUH2cp8uEHi7voWVu5LEvTEowkhDcUkA',
    appId: '1:249052343069:ios:a04ee4a82588789ef2cff4',
    messagingSenderId: '249052343069',
    projectId: 'kelompok2project-disposisi',
    storageBucket: 'kelompok2project-disposisi.appspot.com',
    iosClientId: '249052343069-mkjqoosg6nu102g6emk8cft6022lpian.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelompok2disposisi.RunnerTests',
  );
}
